require("dotenv").config();
const ENV = process.env;
const config = {
    HOST: ENV.APP_HOST,
    PORT: ENV.APP_PORT,
    NODE_DEFAULT: ENV.NODE_DEFAULT,
    ENCRYPT_MSG: ENV.ENCRYPT_MSG || true,
    MIN_AMOUNT: ENV.MIN_AMOUNT,
    CURRENCY: ENV.CURRENCY,
    ALLOWED_CURRENCIES: ['HIVE', 'HBD'],
    HF24_ENABLE: ENV.HF24_ENABLE,
    SOCKET_ENABLE: ENV.SOCKET_ENABLE,
    JWT_SECRET_KEY: ENV.JWT_SECRET_KEY,
    CRYPTR_SECRET_KEY: ENV.CRYPTR_SECRET_KEY,
    REDIS: {
        HOST: ENV.REDIS_HOST,
        PORT: ENV.REDIS_PORT,
        REQUIRE_PASS: false,
        PASSWORD: ENV.REDIS_PASS,
        DB: ENV.REDIS_DB
    }
}
module.exports = config;